### ISSUE TITLE
Enable Vulkan validation layers?

### ISSUE THREAD

**Issue by almarklein** [Korijn/wgpu-bin#6]
In debug mode, wgpu-native uses Vulkan validation layers, which would be nice for debugging. Except that for the messages to be printed to stdout, you'd need to call `env_logger::init()` in Rust ...

> Kvark: I suppose you'd want to have another small Rust library exposing a few C entry points, e.g. for initializing the logger

Alternatively / additionally (?) we can use `VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation`

**Comment by Korijn** [comment]
Is this something we can address in this repo? It doesn't look like it...

**Comment by almarklein** [comment]
From what I understand, wgpu-native has validation layers enabled when compiled in debug mode. The only thing is, we need a Rust call to also have these messages printed to stdout :)

**Comment by Korijn** [comment]
I mean; can we pass that compilation flag to the right command via the makefile? I would think that requires changes upstream. Or alternatively maybe we can use CMake environment variables... not sure.

Adding a rust call is definitely something that would need to be done upstream, right?

**Comment by almarklein** [comment]
Yeah, I think we either need to implement a small wrapper, written in Rust, where we do the call. Or see if it makes sense to add it upstream.

**Comment by almarklein** [comment]
Grr. I updated my drivers in the hope that the grayscale texture tests would work. They don't, but now the `test_rs_compute_tex.py` test fails :(  I think we need the validation layers :/

**Comment by almarklein** [comment]
BTW: whether or not the lib is compiled for debug or release is under our control. Actually, we use `make package` (https://github.com/gfx-rs/wgpu/blob/master/Makefile#L60), which builds both debug and release targets.

**Comment by Korijn** [comment]
Yeah I know, I implemented `make package` upstream! :D Do the debug builds include the stuff you would need?

**Comment by Korijn** [comment]
#8 takes care of publishing debug builds

Moved the `v0.5.1` tag to the new master commit, so that the github release assets will be updated automatically.

see the build running here: https://korijn.visualstudio.com/wgpu-bin/_build/results?buildId=75&view=results

done and published

**Comment by Korijn** [comment]
@almarklein can this be closed?

**Comment by almarklein** [comment]
Yes, I think so.
